services:
  - type: web
    name: ai-career-6months
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ..
      poetry install
    startCommand: poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CHROMA_PATH
        value: ./chroma_db

  - type: web
    name: ai-dashboard
    env: python
    buildCommand: poetry install
    startCommand: poetry run streamlit run dashboards/dashboard.py --server.port 10001 --server.address 0.0.0.0
    