"""Add sentiment and topic columns

Revision ID: 0536e23fe446
Revises: 
Create Date: 2025-10-13 03:06:29.011799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0536e23fe446'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_log', sa.Column('sentiment', sa.String(length=20), nullable=True))
    op.add_column('conversation_log', sa.Column('topic', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_log', 'topic')
    op.drop_column('conversation_log', 'sentiment')
    # ### end Alembic commands ###
